### ISSUE TITLE
Implement `deserialize_option` for `KeyDeserializer`

### ISSUE THREAD

**Issue by indiv0** [serde-rs/xml#15]
Hello! Great library!

I've used this library in one of my projects to deserialize an XML API response, but currently I'm unable to deserialize `Option<String>` types in structs because of the unimplmented `deserialize_option` method in `KeyDeserializer`.

Would it be possible to implement this method?

**Comment by oli-obk** [comment]
sure, that's just an oversight :)

**Comment by indiv0** [comment]
Awesome :)

**Comment by oli-obk** [comment]
Hmm... I'm not so sure anymore. I can deserialize `Option<T>` fields without any problems. Do you have an example XML?

**Comment by indiv0** [comment]
@oli-obk @dtolnay Awesome, thanks!

**Comment by dtolnay** [comment]
@oli-obk will need to publish a release - I don't have permission.

**Comment by indiv0** [comment]
Alrighty.
