### ISSUE TITLE
Deserialization panics at `expected start tag close at ..`

### ISSUE THREAD

**Issue by noisegul** [serde-rs/xml#17]
``` rust
#[test]
fn parse_t() {
    let mut f = File::open("assets/example_map.tmx").unwrap();

    let mut s = String::new();
    f.read_to_string(&mut s).unwrap();

    let m = match serde_xml::de::from_str(&s) {
        Err(e) => panic!("{}", e),
        Ok(d) => d,
    };

    println!("{:?}", m);
}
```

Trying to parse [tmx](https://github.com/bjorn/tiled/blob/master/examples/desert.tmx) files using `serde_xml`, my test as seen above panics with the following message:
`expected start tag close at line 2 column 13`

Is this a bug or am I missing something?

**rustc version**: `rustc 1.11.0-nightly (ad7fe6521 2016-06-23)`

**Comment by oli-obk** [comment]
Can you give me the file you are parsing? Also, what's the type of `m`? How does that even compile xD

**Comment by noisegul** [comment]
The file I am parsing is the one that I linked to above. [This one](https://github.com/bjorn/tiled/blob/master/examples/desert.tmx).
The type of m is `Map`, which currently looks like this:

``` rust
#[derive(Deserialize, Debug)]
pub struct Map {
    version: String,
    orientation: String,
    renderorder: String,
    width: u32,
    height: u32,
    tilewidth: u32,
    tileheight: u32,
    hexsidelength: u32,
    staggeraxis: String,
    staggerindex: String,
    backgroundcolor: Color,
    nextobjectid: u32,
    tileset: Vec<Tileset>,
    layer: Vec<Layer>,
    objectgroup: Vec<ObjectGroup>,
    imagelayer: Vec<ImageLayer>,
    property: Vec<Property>
}

```

(Note that some fields are supposed to be `Optional<>`, but I changed those while trying to isolate the error, it did not make a difference)

The example above is in my `tests/lib.rs` file. My project is organized as a library.

**Comment by dtolnay** [comment]
Looks like the compiler was inferring `m: ()` because of the return type of `rt::begin_panic_fmt` inside the `panic!` macro. You get the same error if you explicitly specify `m: ()`.

Your code needs to say what type to deserialize. It works if you do `let m: Map = match ...`.

**Comment by noisegul** [comment]
That makes sense. I tried it but now I encounter the following error: `serde expected some value: Invalid type. Expected`Unit`at line 0 column 0`.

**Comment by dtolnay** [comment]
Please share the full code that is not working.

**Comment by noisegul** [comment]
I was able to fix the error and my code works as intended now, thank you for your help =) .
It was actually caused by my structs being malformed, taking the `Map` example above: making the attributes missing in the XML actually optional, all of them, same for the additional structs being used inside `Map`.

However: 
The error message `Expected Unit at line 0 column 0'` stays the same regardless the wrongly declared field and regardless of the struct containing the wrong declaration.

**Comment by oli-obk** [comment]
Error reporting is definitely suboptimal right now. I'll look into it.
