### ISSUE TITLE
`serde_xml::from_str` yields error on Rust nightly and newest crate versions

### ISSUE THREAD

**Issue by noisegul** [serde-rs/xml#20]
``` rust
    let m: Map = match serde_xml::from_str(&s) {
        Err(e) => panic!("{}", e),
        Ok(d) => d,
    };
```

breaks with newest `cargo update` to `serde v0.8.0` and now produces the error `the trait bound til::mps::Map: serde::de::Deserialize is not satisfied [E0277]`.

**[dependencies]**
serde = "*"
serde_macros = "*"
serde_xml = "*"

**rustc --version**
rustc 1.12.0-nightly (feeca9457 2016-07-26)

**Comment by oli-obk** [comment]
please, please do NOT use `"*"` imports. Never ever.

The issue you are seeing is exactly due to the `"*"` imports.

I have not yet updated `serde_xml` to `serde 0.8`, so there's no way that could ever work.

**Comment by noisegul** [comment]
You are right, I missed that `serde_xml` was running on `serde v0.7.15`, thank you for the general advice and quick answer.

**Comment by oli-obk** [comment]
I added serde-xml 0.8 to crates.io
