### ISSUE TITLE
Out of order list of tags deserialization error

### ISSUE THREAD

**Issue by indiv0** [serde-rs/xml#33]
So I basically have some XML in the form:

```xml
<states>
  <state />
  <statelist>
    <state />
    <state />
  </statelist>
  <state />
</states>
```

which fails to deserialize because the tags go `state`, `statelist`, `state`.

However it deserializes fine if the two `state` tags come first:

```xml
<states>
  <state />
  <state />
  <statelist>
    <state />
    <state />
  </statelist>
</states>
```

**Comment by oli-obk** [comment]
To what rust code do you expect it to deserialize? I have no clue how to represent interleaved sequences.

**Comment by oli-obk** [comment]
See #26 for a similar/the same case

**Comment by indiv0** [comment]
I expect/prefer for it to deserialize to:

```rust
struct States {
    state: Vec<State>,
    statelist: Statelist,
}

struct Statelist {
    state: Vec<State>,
}
```

i.e., merge the sequences into a single `Vec`, as if all the elements came in order.

**Comment by oli-obk** [comment]
There can't be multiple state lists?

This is very hard to do, I'll think about it, but it'll require some intermediate allocations.

The easiest would be to manually implement deserialize for this special case

**Comment by indiv0** [comment]
There can be multiple statelists, but I simplified it for the purposes of illustrating the example. [Here's](https://github.com/indiv0/wolfram-alpha-rs/blob/19b71bf086bce879b3151bbbc425921072b37950/src/model.in.rs#L256-L282) the full version of what I want.

Let me know what you've decided when you've finished thinking about it. If it's indeed too hard to handle then I guess I can write a custom deserializer.

**Comment by oli-obk** [comment]
The serde deserialization framework does not fit your use case with autogenerated deserialize impls. There's no need for a custom deserializer, since that won't help. You need to implement `Deserialize` manually for  `States`.

I'd still say that the solution from #26 is cleaner, but I'm not sure on the usability of the struct and enum

**Comment by indiv0** [comment]
Yeah that's what I meant by "custom deserializer". Ok I'll look into it, thanks.

**Comment by indiv0** [comment]
Actually, I don't think I can use the solution in #26 because my elements don't specify an `xsi:type`. Is there a way to deserialize those elements to an enum just on their name alone?

**Comment by oli-obk** [comment]
Yea, you need to write a `MapVisitor` to get access to the names

**Comment by oli-obk** [comment]
Similar to the generic one [here](https://github.com/serde-rs/xml/blob/master/src/de/mod.rs#L627) you can simply call a `KeyDeserializer` to get the name

**Comment by indiv0** [comment]
Well for what's its worth I ended up implementing `Deserialize` manually and leaving the struct itself as-is. It seems to work. Thank you for your help. I guess this issue can be closed now.
