### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by Ronaldho80** [serde-rs/xml#6]
Hello,

when I compile, I get the errors below. Did I forget something?

Thx,
Ronny

duke@LubuntuVM:~/rust/xml$ cargo build 
   Compiling serde_xml v0.0.1 (file:///home/duke/rust/xml)
src/de/value.rs:115:5: 119:6 error: method `visit_seq` is not a member of trait `de::VariantVisitor`
src/de/value.rs:115     fn visit_seq<V>(&mut self, _visitor: V) -> Result<V::Value, Self::Error>
src/de/value.rs:116         where V: de::Visitor
src/de/value.rs:117     {
src/de/value.rs:118         unimplemented!()
src/de/value.rs:119     }
src/de/value.rs:122:5: 135:6 error: method `visit_map` is not a member of trait `de::VariantVisitor`
src/de/value.rs:122     fn visit_map<V>(&mut self, mut visitor: V) -> Result<V::Value, Self::Error>
src/de/value.rs:123         where V: de::Visitor
src/de/value.rs:124     {
src/de/value.rs:125         debug!("VariantVisitor::visit_map\n");
src/de/value.rs:126         let el = self.0.take().unwrap();
src/de/value.rs:127         visitor.visit_map(MapDeserializer {
                    ...
src/de/mod.rs:115:5: 119:6 error: method `visit_named_unit` is not a member of trait `de::Deserializer`
src/de/mod.rs:115     fn visit_named_unit<V>(&mut self, _name: &str, _visitor: V) -> Result<V::Value, Error>
src/de/mod.rs:116         where V: de::Visitor,
src/de/mod.rs:117     {
src/de/mod.rs:118         unimplemented!()
src/de/mod.rs:119     }
src/de/mod.rs:121:5: 125:6 error: method `visit_named_seq` is not a member of trait `de::Deserializer`
src/de/mod.rs:121     fn visit_named_seq<V>(&mut self, _name: &str, _visitor: V) -> Result<V::Value, Error>
src/de/mod.rs:122         where V: de::Visitor,
src/de/mod.rs:123     {
src/de/mod.rs:124         unimplemented!()
src/de/mod.rs:125     }
src/de/mod.rs:327:5: 331:6 error: method `visit_seq` is not a member of trait `de::VariantVisitor`
src/de/mod.rs:327     fn visit_seq<V>(&mut self, _visitor: V) -> Result<V::Value, Self::Error>
src/de/mod.rs:328         where V: de::Visitor
src/de/mod.rs:329     {
src/de/mod.rs:330         unimplemented!()
src/de/mod.rs:331     }
src/de/mod.rs:334:5: 339:6 error: method `visit_map` is not a member of trait `de::VariantVisitor`
src/de/mod.rs:334     fn visit_map<V>(&mut self, mut visitor: V) -> Result<V::Value, Self::Error>
src/de/mod.rs:335         where V: de::Visitor
src/de/mod.rs:336     {
src/de/mod.rs:337         try!(self.0.bump());
src/de/mod.rs:338         visitor.visit_map(ContentVisitor::new_attr(&mut self.0))
src/de/mod.rs:339     }
src/error.rs:94:5: 96:6 error: method `syntax_error` is not a member of trait `de::Error`
src/error.rs:94     fn syntax_error() -> Error {
src/error.rs:95         Error::SyntaxError(SerdeExpectedSomeValue, 0, 0)
src/error.rs:96     }
src/error.rs:98:5: 100:6 error: method `unknown_field_error` is not a member of trait `de::Error`
src/error.rs:98     fn unknown_field_error(field: &str) -> Error {
src/error.rs:99         Error::UnknownField(field.to_string())
src/error.rs:100     }
src/error.rs:102:5: 104:6 error: method `end_of_stream_error` is not a member of trait `de::Error`
src/error.rs:102     fn end_of_stream_error() -> Error {
src/error.rs:103         Error::SyntaxError(EOF, 0, 0)
src/error.rs:104     }
src/error.rs:106:5: 108:6 error: method `missing_field_error` is not a member of trait `de::Error`
src/error.rs:106     fn missing_field_error(field: &'static str) -> Error {
src/error.rs:107         Error::MissingFieldError(field)
src/error.rs:108     }
error: aborting due to 10 previous errors
Could not compile `serde_xml`.

**Comment by oli-obk** [comment]
sorry I was on vacation, this was fixed in the unmerged #5 and is being fixed even better in #7
